openapi: 3.0.0
info:
  title: Grocery
  version: 1.0.0
servers:
  - url: localhost://5000
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    apikeyAuth:
      type: http
      scheme: apikey
tags:
  - name: UserAPI
  - name: ApprovalAPI
  - name: SectionAPI
  - name: ProductAPI
  - name: CartAPI
  - name: PurchaseAPI
paths:
  /api/login:
    post:
      tags:
        - UserAPI
      summary: API Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@email.com
                password: admin
      security:
        - noauthAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Sun, 31 Dec 2023 10:44:13 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '150'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                email: admin@email.com
                role: admin
                token: >-
                  WyJiYmE4NGZkMDE3YjA0NTVkODY5OWJjODFkOGE1MzYyMiJd.ZZFF_Q.tdZOeTwK0TI4O5JSt5Re6HTC6Wo
  /api/user:
    post:
      tags:
        - UserAPI
      summary: REGISTER
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: manager12@email.com
                password: manager
                role: manager
      responses:
        '201':
          description: CREATED
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:03:42 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '47'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: successfully registered!!
    get:
      tags:
        - UserAPI
      summary: GET USERS
      security:
        - apikeyAuth: []
      parameters:
        - name: Authentication-Token
          in: header
          schema:
            type: string
          example: >-
            WyJiYmE4NGZkMDE3YjA0NTVkODY5OWJjODFkOGE1MzYyMiJd.ZZBiig.x2pXcB132mFqZH6F8PgGw2N8fSk
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:04:04 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1286'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  email: admin@email.com
                  active: true
                  role: admin
                - id: 2
                  email: manager@email.com
                  active: true
                  role: manager
                - id: 3
                  email: manager2@email.com
                  active: true
                  role: manager
                - id: 4
                  email: user@email.com
                  active: true
                  role: user
                - id: 5
                  email: user2@email.com
                  active: true
                  role: user
                - id: 6
                  email: manager2@gmail.com
                  active: true
                  role: manager
                - id: 7
                  email: sahil@email.com
                  active: true
                  role: user
                - id: 8
                  email: manager3@email.com
                  active: true
                  role: manager
                - id: 9
                  email: user3@email.com
                  active: true
                  role: user
                - id: 10
                  email: manager30@email.com
                  active: true
                  role: manager
                - id: 11
                  email: manager12@email.com
                  active: false
                  role: manager
    put:
      tags:
        - UserAPI
      summary: CHANGE PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                password: new password
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 19:38:41 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '51'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Password changed successfully!!
  /api/auth/verify:
    post:
      tags:
        - UserAPI
      summary: VERIFY AUTH
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: manager@email.com
                role: manager
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:08:49 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '34'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Token is valid
  /api/approvals:
    get:
      tags:
        - ApprovalAPI
      summary: GET APPROVALS
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:14:53 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '3334'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  description: approve creation of manager
                  requester_id: 6
                  section_id: null
                  status: rejected
                - id: 2
                  description: approve creation of section
                  requester_id: 2
                  section_id: 1
                  status: approved
                - id: 3
                  description: approve creation of manager
                  requester_id: 6
                  section_id: null
                  status: approved
                - id: 4
                  description: approve creation of section
                  requester_id: 2
                  section_id: 1
                  status: rejected
                - id: 5
                  description: approve creation of manager
                  requester_id: 8
                  section_id: null
                  status: approved
                - id: 6
                  description: approve creation of section
                  requester_id: 2
                  section_id: 4
                  status: rejected
                - id: 7
                  description: approve deletion of section
                  requester_id: 2
                  section_id: 2
                  status: rejected
                - id: 8
                  description: approve creation of section
                  requester_id: 2
                  section_id: 8
                  status: rejected
                - id: 9
                  description: approve creation of section
                  requester_id: 2
                  section_id: 8
                  status: rejected
                - id: 10
                  description: approve creation of section
                  requester_id: 2
                  section_id: 9
                  status: rejected
                - id: 11
                  description: approve creation of manager
                  requester_id: 10
                  section_id: null
                  status: approved
                - id: 12
                  description: approve creation of section
                  requester_id: 2
                  section_id: 3
                  status: approved
                - id: 13
                  description: approve creation of section
                  requester_id: 2
                  section_id: 4
                  status: approved
                - id: 14
                  description: approve creation of section
                  requester_id: 2
                  section_id: 5
                  status: approved
                - id: 15
                  description: approve creation of section
                  requester_id: 2
                  section_id: 6
                  status: rejected
                - id: 16
                  description: approve creation of section
                  requester_id: 2
                  section_id: 6
                  status: approved
                - id: 17
                  description: approve creation of section
                  requester_id: 2
                  section_id: 7
                  status: rejected
                - id: 18
                  description: approve creation of manager
                  requester_id: 11
                  section_id: null
                  status: rejected
                - id: 19
                  description: approve creation of section
                  requester_id: 2
                  section_id: 7
                  status: approved
                - id: 20
                  description: approve creation of manager
                  requester_id: 11
                  section_id: null
                  status: pending
  /api/approve/5:
    put:
      tags:
        - ApprovalAPI
      summary: APPROVE
      requestBody:
        content: {}
      security:
        - apikeyAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
          example: approve
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:15:03 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '36'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Already approved
  /api/section:
    get:
      tags:
        - SectionAPI
      summary: GET SECTIONS
      description: |-
        optional parameters

        - section_id
            
        - active = true/false
      security:
        - apikeyAuth: []
      parameters:
        - name: name
          in: query
          schema:
            type: string
          example: medicine
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:15:37 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '3710'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  name: meds
                  creator_id: 1
                  active: 'True'
                  products:
                    - id: 1
                      name: vicks
                      description: medicine
                      price: 3
                      section_id: 1
                      unit: 'N'
                      stock: 0
                      created_at: Mon, 22 Jan 2024 14:22:06 -0000
                      expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                    - id: 2
                      name: vicks
                      description: medss
                      price: 5
                      section_id: 1
                      unit: g
                      stock: 0
                      created_at: Mon, 22 Jan 2024 14:23:46 -0000
                      expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                    - id: 3
                      name: voc
                      description: ff
                      price: 44
                      section_id: 1
                      unit: dozen
                      stock: 0
                      created_at: Mon, 22 Jan 2024 14:25:27 -0000
                      expired_at: Wed, 24 Jan 2024 00:00:00 -0000
                    - id: 4
                      name: vv
                      description: cdv
                      price: 333
                      section_id: 1
                      unit: /Kg
                      stock: 4
                      created_at: Mon, 22 Jan 2024 14:27:23 -0000
                      expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                    - id: 6
                      name: toffee
                      description: candy
                      price: 10
                      section_id: 1
                      unit: /Kg
                      stock: 9
                      created_at: Tue, 23 Jan 2024 12:45:40 -0000
                      expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                - id: 2
                  name: dairy
                  creator_id: 1
                  active: 'True'
                  products:
                    - id: 5
                      name: milk
                      description: mmmm
                      price: 33
                      section_id: 2
                      unit: /L
                      stock: 1
                      created_at: Mon, 22 Jan 2024 14:32:26 -0000
                      expired_at: Wed, 17 Jan 2024 00:00:00 -0000
                    - id: 7
                      name: toffee
                      description: |
                        candy
                      price: 30
                      section_id: 2
                      unit: 'N'
                      stock: 30
                      created_at: Tue, 23 Jan 2024 15:00:22 -0000
                      expired_at: Wed, 31 Jan 2024 00:00:00 -0000
                - id: 3
                  name: groceries
                  creator_id: 2
                  active: 'True'
                  products: []
                - id: 4
                  name: cleaning
                  creator_id: 2
                  active: 'True'
                  products: []
                - id: 5
                  name: candies
                  creator_id: 2
                  active: 'True'
                  products: []
                - id: 6
                  name: groceries12
                  creator_id: 2
                  active: 'True'
                  products: []
                - id: 7
                  name: toys
                  creator_id: 2
                  active: 'True'
                  products: []
                - id: 8
                  name: medicine
                  creator_id: 1
                  active: 'True'
                  products: []
    post:
      tags:
        - SectionAPI
      summary: CREATE SECTION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: medicine
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:15:25 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '103'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 8
                name: medicine
                creator_id: 1
                active: 'True'
                products: []
  /api/section/8:
    delete:
      tags:
        - SectionAPI
      summary: DELETE SECTION
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:15:43 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '50'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Section deleted successfully!!
  /api/section/2:
    put:
      tags:
        - SectionAPI
      summary: EDIT SECTION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: groceries
      security:
        - apikeyAuth: []
      parameters:
        - name: Authentication-Token
          in: header
          schema:
            type: string
          example: >-
            WyIzZDUwYzc1ZDEyZjQ0MjBiODcxZmU5MmVkNzRlYWRiMCJd.Zay7Uw.KaV_jTXzSq4cWGiwCUAANQNkDCw
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:16:10 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1773'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1
                name: medicine
                creator_id: 1
                active: 'True'
                products:
                  - id: 1
                    name: vicks
                    description: medicine
                    price: 3
                    section_id: 1
                    unit: 'N'
                    stock: 0
                    created_at: Mon, 22 Jan 2024 14:22:06 -0000
                    expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                  - id: 2
                    name: vicks
                    description: medss
                    price: 5
                    section_id: 1
                    unit: g
                    stock: 0
                    created_at: Mon, 22 Jan 2024 14:23:46 -0000
                    expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                  - id: 3
                    name: voc
                    description: ff
                    price: 44
                    section_id: 1
                    unit: dozen
                    stock: 0
                    created_at: Mon, 22 Jan 2024 14:25:27 -0000
                    expired_at: Wed, 24 Jan 2024 00:00:00 -0000
                  - id: 4
                    name: vv
                    description: cdv
                    price: 333
                    section_id: 1
                    unit: /Kg
                    stock: 4
                    created_at: Mon, 22 Jan 2024 14:27:23 -0000
                    expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                  - id: 6
                    name: toffee
                    description: candy
                    price: 10
                    section_id: 1
                    unit: /Kg
                    stock: 9
                    created_at: Tue, 23 Jan 2024 12:45:40 -0000
                    expired_at: Fri, 02 Feb 2024 00:00:00 -0000
  /api/product:
    get:
      tags:
        - ProductAPI
      summary: GET PRODUCTS
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:31:30 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '2785'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  name: vicks
                  description: medicine
                  price: 3
                  section_id: 1
                  seller_id: 10
                  unit: 'N'
                  stock: 0
                  created_at: Mon, 22 Jan 2024 14:22:06 -0000
                  expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                  section:
                    id: 1
                    name: medicine
                - id: 2
                  name: vicks
                  description: medss
                  price: 5
                  section_id: 1
                  seller_id: 10
                  unit: g
                  stock: 0
                  created_at: Mon, 22 Jan 2024 14:23:46 -0000
                  expired_at: Thu, 25 Jan 2024 00:00:00 -0000
                  section:
                    id: 1
                    name: medicine
                - id: 3
                  name: voc
                  description: ff
                  price: 44
                  section_id: 1
                  seller_id: 10
                  unit: dozen
                  stock: 0
                  created_at: Mon, 22 Jan 2024 14:25:27 -0000
                  expired_at: Wed, 24 Jan 2024 00:00:00 -0000
                  section:
                    id: 1
                    name: medicine
                - id: 4
                  name: vv
                  description: cdv
                  price: 333
                  section_id: 1
                  seller_id: 10
                  unit: /Kg
                  stock: 4
                  created_at: Mon, 22 Jan 2024 14:27:23 -0000
                  expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                  section:
                    id: 1
                    name: medicine
                - id: 5
                  name: milk
                  description: mmmm
                  price: 33
                  section_id: 2
                  seller_id: 10
                  unit: /L
                  stock: 1
                  created_at: Mon, 22 Jan 2024 14:32:26 -0000
                  expired_at: Wed, 17 Jan 2024 00:00:00 -0000
                  section:
                    id: 2
                    name: dairy
                - id: 6
                  name: toffee
                  description: candy
                  price: 10
                  section_id: 1
                  seller_id: 2
                  unit: /Kg
                  stock: 9
                  created_at: Tue, 23 Jan 2024 12:45:40 -0000
                  expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                  section:
                    id: 1
                    name: medicine
                - id: 7
                  name: toffee
                  description: |
                    candy
                  price: 30
                  section_id: 2
                  seller_id: 2
                  unit: 'N'
                  stock: 30
                  created_at: Tue, 23 Jan 2024 15:00:22 -0000
                  expired_at: Wed, 31 Jan 2024 00:00:00 -0000
                  section:
                    id: 2
                    name: dairy
    post:
      tags:
        - ProductAPI
      summary: CREATE PRODUCT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: vicks
                description: khich khich door karo
                section_id: 1
                price: 1
                unit: 'N'
                stock: 3000
                expired_at: '2024-01-31'
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:34:30 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '350'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 8
                name: vicks
                description: khich khich door karo
                price: 1
                section_id: 1
                seller_id: 2
                unit: 'N'
                stock: 3000
                created_at: Wed, 24 Jan 2024 18:34:30 -0000
                expired_at: Wed, 31 Jan 2024 00:00:00 -0000
                section:
                  id: 1
                  name: medicine
  /api/product/8:
    delete:
      tags:
        - ProductAPI
      summary: DELETE PRODUCT
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:34:46 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '50'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Product deleted successfully
  /api/product/1:
    put:
      tags:
        - ProductAPI
      summary: New Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                name: vicks
                description: kharaash
                price: 3
                section_id: 2
                seller_id: 9
                unit: 'N'
                stock: 10
                created_at: Sun, 21 Jan 2024 13:18:19 -0000
                expired_at: '2024-02-06'
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:34:56 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '333'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1
                name: vicks
                description: kharaash
                price: 3
                section_id: 2
                seller_id: 10
                unit: 'N'
                stock: 10
                created_at: Mon, 22 Jan 2024 14:22:06 -0000
                expired_at: Tue, 06 Feb 2024 00:00:00 -0000
                section:
                  id: 2
                  name: dairy
  /api/cart:
    get:
      tags:
        - CartAPI
      summary: GET CART
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:41:34 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '796'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 5
                  product:
                    id: 6
                    name: toffee
                    description: candy
                    price: 10
                    section_id: 1
                    unit: /Kg
                    stock: 9
                    created_at: Tue, 23 Jan 2024 12:45:40 -0000
                    expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                  quantity: 3
                - id: 7
                  product:
                    id: 4
                    name: vv
                    description: cdv
                    price: 333
                    section_id: 1
                    unit: /Kg
                    stock: 4
                    created_at: Mon, 22 Jan 2024 14:27:23 -0000
                    expired_at: Fri, 02 Feb 2024 00:00:00 -0000
                  quantity: 1
    post:
      tags:
        - CartAPI
      summary: ADD PRODUCT TO CART
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product_id: 4
                quantity: 1
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:41:29 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '43'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Added product to cart
  /api/cart/7:
    delete:
      tags:
        - CartAPI
      summary: DELETE CART ITEM
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:41:57 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '49'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Cart deleted successfully!!
  /api/purchase:
    get:
      tags:
        - PurchaseAPI
      summary: GET PURCHASES
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:42:20 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '8744'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 31
                  user_id: 5
                  order_id: 8ffaae09886d4e77810cac285e000dbe
                  purchase_date: Tue, 23 Jan 2024 21:47:14 -0000
                  product_id: 4
                  quantity: 4
                  product:
                    name: vv
                    price: 333
                - id: 32
                  user_id: 5
                  order_id: 8ffaae09886d4e77810cac285e000dbe
                  purchase_date: Tue, 23 Jan 2024 21:47:14 -0000
                  product_id: 6
                  quantity: 4
                  product:
                    name: toffee
                    price: 10
                - id: 29
                  user_id: 5
                  order_id: 1066b3f6e9ae43a198df25baac9f6664
                  purchase_date: Tue, 23 Jan 2024 21:07:35 -0000
                  product_id: 4
                  quantity: 18
                  product:
                    name: vv
                    price: 333
                - id: 30
                  user_id: 5
                  order_id: 1066b3f6e9ae43a198df25baac9f6664
                  purchase_date: Tue, 23 Jan 2024 21:07:35 -0000
                  product_id: 6
                  quantity: 2
                  product:
                    name: toffee
                    price: 10
                - id: 27
                  user_id: 5
                  order_id: aa9455caf4b04013bc6b3ae6cafe6e6e
                  purchase_date: Tue, 23 Jan 2024 20:56:06 -0000
                  product_id: 6
                  quantity: 2
                  product:
                    name: toffee
                    price: 10
                - id: 28
                  user_id: 5
                  order_id: aa9455caf4b04013bc6b3ae6cafe6e6e
                  purchase_date: Tue, 23 Jan 2024 20:56:06 -0000
                  product_id: 4
                  quantity: 1
                  product:
                    name: vv
                    price: 333
                - id: 25
                  user_id: 5
                  order_id: 1ef55a82d1cd456c9c27bd08966804bf
                  purchase_date: Tue, 23 Jan 2024 20:53:54 -0000
                  product_id: 6
                  quantity: 3
                  product:
                    name: toffee
                    price: 10
                - id: 26
                  user_id: 5
                  order_id: 1ef55a82d1cd456c9c27bd08966804bf
                  purchase_date: Tue, 23 Jan 2024 20:53:54 -0000
                  product_id: 5
                  quantity: 1
                  product:
                    name: milk
                    price: 33
                - id: 24
                  user_id: 5
                  order_id: b4fa4e1b8b1740dbb44d449bb445213c
                  purchase_date: Tue, 23 Jan 2024 20:27:05 -0000
                  product_id: 5
                  quantity: 2
                  product:
                    name: milk
                    price: 33
                - id: 23
                  user_id: 5
                  order_id: c9effaa676bb408dafe93e6d6852ce60
                  purchase_date: Tue, 23 Jan 2024 16:52:15 -0000
                  product_id: 5
                  quantity: 12
                  product:
                    name: milk
                    price: 33
                - id: 20
                  user_id: 5
                  order_id: 5d99a818bedf46f78ad8e92df81ff6aa
                  purchase_date: Tue, 23 Jan 2024 16:26:13 -0000
                  product_id: 3
                  quantity: 1
                  product:
                    name: voc
                    price: 44
                - id: 21
                  user_id: 5
                  order_id: 5d99a818bedf46f78ad8e92df81ff6aa
                  purchase_date: Tue, 23 Jan 2024 16:26:13 -0000
                  product_id: 5
                  quantity: 17
                  product:
                    name: milk
                    price: 33
                - id: 22
                  user_id: 5
                  order_id: 5d99a818bedf46f78ad8e92df81ff6aa
                  purchase_date: Tue, 23 Jan 2024 16:26:13 -0000
                  product_id: 4
                  quantity: 6
                  product:
                    name: vv
                    price: 333
                - id: 18
                  user_id: 5
                  order_id: acf74875ffb04f489676d034518f6fb1
                  purchase_date: Mon, 22 Jan 2024 21:18:52 -0000
                  product_id: 3
                  quantity: 3
                  product:
                    name: voc
                    price: 44
                - id: 19
                  user_id: 5
                  order_id: acf74875ffb04f489676d034518f6fb1
                  purchase_date: Mon, 22 Jan 2024 21:18:52 -0000
                  product_id: 1
                  quantity: 1
                  product:
                    name: vicks
                    price: 3
                - id: 17
                  user_id: 5
                  order_id: 72816f7c7e644b068a37176b2291d078
                  purchase_date: Mon, 22 Jan 2024 20:26:56 -0000
                  product_id: 2
                  quantity: 55
                  product:
                    name: vicks
                    price: 5
                - id: 16
                  user_id: 5
                  order_id: 2d4fad236cc84524acbbb98f70b2a4d5
                  purchase_date: Mon, 22 Jan 2024 20:24:15 -0000
                  product_id: 1
                  quantity: 16
                  product:
                    name: vicks
                    price: 3
                - id: 15
                  user_id: 5
                  order_id: 4b5fcd35587d4fe0b96dcce15aedabc0
                  purchase_date: Mon, 22 Jan 2024 20:22:59 -0000
                  product_id: 1
                  quantity: 16
                  product:
                    name: vicks
                    price: 3
                - id: 13
                  user_id: 5
                  order_id: f1591d2dbd344003b6703a07d07ecbdb
                  purchase_date: Mon, 22 Jan 2024 18:00:41 -0000
                  product_id: 0
                  quantity: 16
                  product:
                    name: null
                    price: null
                - id: 14
                  user_id: 5
                  order_id: f1591d2dbd344003b6703a07d07ecbdb
                  purchase_date: Mon, 22 Jan 2024 18:00:41 -0000
                  product_id: 0
                  quantity: 8
                  product:
                    name: null
                    price: null
                - id: 12
                  user_id: 5
                  order_id: d42b8d8418f442b289498f18a027c389
                  purchase_date: Sun, 21 Jan 2024 22:49:46 -0000
                  product_id: 0
                  quantity: 11
                  product:
                    name: null
                    price: null
                - id: 11
                  user_id: 5
                  order_id: f99f500ba894497cbfa58a00a1d8952b
                  purchase_date: Sun, 21 Jan 2024 22:25:48 -0000
                  product_id: 0
                  quantity: 5
                  product:
                    name: null
                    price: null
                - id: 10
                  user_id: 5
                  order_id: a0c4945d6e3043dc96cad163ace7ce9f
                  purchase_date: Sun, 21 Jan 2024 10:39:24 -0000
                  product_id: 0
                  quantity: 8
                  product:
                    name: null
                    price: null
                - id: 9
                  user_id: 5
                  order_id: 80cb0c1045d64ab6b515b42385c2d868
                  purchase_date: Sun, 21 Jan 2024 10:17:41 -0000
                  product_id: 0
                  quantity: 4
                  product:
                    name: null
                    price: null
                - id: 7
                  user_id: 5
                  order_id: e503691792704b98ae6acbb78a425044
                  purchase_date: Sun, 21 Jan 2024 10:04:48 -0000
                  product_id: 0
                  quantity: 5
                  product:
                    name: null
                    price: null
                - id: 8
                  user_id: 5
                  order_id: e503691792704b98ae6acbb78a425044
                  purchase_date: Sun, 21 Jan 2024 10:04:48 -0000
                  product_id: 0
                  quantity: 4
                  product:
                    name: null
                    price: null
                - id: 6
                  user_id: 5
                  order_id: a619d78fd8074cb596622f8fbe4ae9f3
                  purchase_date: Sun, 21 Jan 2024 10:02:34 -0000
                  product_id: 0
                  quantity: 2
                  product:
                    name: null
                    price: null
                - id: 4
                  user_id: 5
                  order_id: 556ff1848b50486abf797d5121513749
                  purchase_date: Sun, 21 Jan 2024 09:59:33 -0000
                  product_id: 0
                  quantity: 2
                  product:
                    name: null
                    price: null
                - id: 5
                  user_id: 5
                  order_id: 556ff1848b50486abf797d5121513749
                  purchase_date: Sun, 21 Jan 2024 09:59:33 -0000
                  product_id: 0
                  quantity: 20
                  product:
                    name: null
                    price: null
    post:
      tags:
        - PurchaseAPI
      summary: MAKE PURCHASE
      requestBody:
        content: {}
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: number
                example: Werkzeug/3.0.1 Python/3.10.0
            Date:
              schema:
                type: string
                example: Wed, 24 Jan 2024 18:42:37 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '101'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Vary:
              schema:
                type: string
                example: Cookie
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                message: Purchase created successfully!!
                order_id: c30b94f6eda9497aafcb40733cdd7b83
  /api/purchase/c30b94f6eda9497aafcb40733cdd7b83:
    delete:
      tags:
        - PurchaseAPI
      summary: DELETE PURCHASE
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
